### ISSUE TITLE
Deduplication

### ISSUE THREAD

**Issue by mfbrj** [Storj/metacore#13]
An idea to implement a file level deduplication:

On the client:

```
Before upload a file:
  hash = file.hash()
  If storj_network.exists(hash) then
    storj_network.increase_hash_counter(hash)
  else storj_network.upload(file.encrypted(), hash)
  storj_network.user.increase_used_space(file.size())
```

```
Before delete a file:
  hash = file.hash()
  storj_network.decrease_hash_counter(hash)
  storj_network.user.decrease_used_space(file.size())
```

On storj network:

```
if storj_network.hash_counter(hash) == 0 then
  storj_network.delete(file)
```

Concerns:
- Files with high hash counts must be spreaded on several driveshares nodes to grant high availability?

**Comment by super3** [comment]
Doesn't solve the underling privacy problems with deduplication. By using this collision I can easily tell what files you have if they are common files. Best to encrypt everything differently by default, and work on a more secure deduplication algo later.
