### ISSUE TITLE
Blacklist.txt Usage Unclear

### ISSUE THREAD

**Issue by super3** [Storj/metacore#20]
SSHed in and added a hash to the blacklist, and it was still able to download that content. I'm assuming I'm just using it wrong. Please add some documentation on how to use it properly.

**Comment by ViktorovEugene** [comment]
How I can see, you added hash to the /root/metacore/metacore/Blacklist.txt, but the node app are runnign in the docker's container. I've added the same hash to he docker's Blacklist.txt. Try it now.

**Comment by super3** [comment]
Ok, can you add some documentation on how to properly add a hash to the docker container's blacklist? Have not worked with docker before, so not exactly sure what do to.

**Comment by ViktorovEugene** [comment]
Yes but, if you don't mind, I'll do it in Monday))

**Comment by super3** [comment]
Sure

**Comment by ViktorovEugene** [comment]
Done! Try it. I think that, how to interchange some data with the container, or how to sharing a directory with container, should be described asewll.  Hovever, this issue is explicated at the https://docs.docker.com/engine/userguide/dockervolumes/.
